// <auto-generated />
namespace DataAccessProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class makigDateTypeNullable_OneWasMissing_Ups : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(makigDateTypeNullable_OneWasMissing_Ups));
        
        string IMigrationMetadata.Id
        {
            get { return "201410201247355_makigDateTypeNullable_OneWasMissing_Ups"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
